### PR TITLE
Added CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by FahimFBA**
closing #24

### CODE REVIEW

**Comment by Lakr233** [comment]
I'm working hard on some feature, will come back later.

**Comment by FahimFBA** [comment]
Sure! Take your time.

**Comment by ryh** [comment]
@FahimFBA I believe this kind of document should be drafted by the project author, You are overstepping.
It is not your right to tell community what to do.

**Comment by Lakr233** [comment]
Don't blame people that are trying to help tho. 😝

I'm currently working on SFTP will check this pull request later.

**Comment by ryh** [comment]
@Lakr233 推荐阅读 [起家于俄罗斯的NGINX开源项目宣布禁俄，不知NGINX之父怎么想？](https://mp.weixin.qq.com/s/_gAhftpIRiJiIGTubLU3xg) 项目被社区裹挟的实例 而nginx就是被所谓的Contributor Covenant 怂恿（甚至说是控制）的 https://github.com/nginxinc/Community-Code-of-Conduct

**Pull request closed without merging**
